apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jboss-jboss-app-2
  title: JBoss - jboss-app-2
  annotations:
    jboss.io/stato: running
    jboss.io/host-port: "8082"
    jboss.io/image-tag: "1.0"
    jenkins.io/job-full-name: "ansible-jboss"
spec:
  type: jboss-instance
  lifecycle: experimental
  owner: user:guest
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jboss-jboss-app-3
  title: JBoss - jboss-app-3
  annotations:
    jboss.io/stato: running
    jboss.io/host-port: "8083"
    jboss.io/image-tag: "1.0"
    jenkins.io/job-full-name: "ansible-jboss"
spec:
  type: jboss-instance
  lifecycle: experimental
  owner: user:guest
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jboss-jboss-app-5
  title: JBoss - jboss-app-5
  annotations:
    jboss.io/stato: building
    jboss.io/host-port: "8085"
    jboss.io/image-tag: "1.0"
    jenkins.io/job-full-name: "ansible-jboss"
spec:
  type: jboss-instance
  lifecycle: experimental
  owner: user:guest
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jboss-jboss-app
  title: JBoss - jboss-app
  annotations:
    jboss.io/stato: running
    jboss.io/host-port: "8081"
    jboss.io/image-tag: "1.0"
    jenkins.io/job-full-name: "ansible-jboss"
spec:
  type: jboss-instance
  lifecycle: experimental
  owner: user:guest
